### ISSUE TITLE
dwyl t-shirts

### ISSUE THREAD

**Issue by iteles** [dwyl/start-here#16]
These will most likely turn into a 'uniform' of sorts. And I would *definitely* wear some 'do what you love' t-shirts as part of my day-to-day wardrobe!  [Trying hard not to spin this off into a clothing line - I see [brush script](http://likeletterprojects.com/2013/wp-content/uploads/2014/01/391a54e47c2111e3a6680e0368da678b_8.jpg) in our future].

Tasks:
- [ ] Determine types of t-shirts
- [ ] Define budget
- [ ] Research and get quotes for screenprinted t-shirts
- [ ] Define print colours and sizes
- [ ] Define tee sizes and numbers required
- [ ] Order

**Comment by nelsonic** [comment]
@iteles as discussed, this *issue* deserves its own REPOsitory ...
We don't want all the (*hard*) work that goes into making *great* T's to be buried in an *issue* on a another repo...

**Comment by nelsonic** [comment]
![dwyl-tshirts-ines-email](https://cloud.githubusercontent.com/assets/194400/8124093/83c217ba-10cd-11e5-91e3-0e3f3da21eee.png)

**Comment by nelsonic** [comment]
For others who are following along, we are talking about these T-Shirts: https://wholesale.bella.com/product/3413/howard-tee.html

![bella canvas-t-shirts-in-teal](https://cloud.githubusercontent.com/assets/194400/8124111/d45bb1c2-10cd-11e5-8112-7f71299d78ef.png)
 
Agree that the T's are (relatively) expensive... 
But... in the scheme of things, this is (*one of*) the ***best investments*** we can make.
We want the best quality T's ***possible*** so people *wear* them!

Even though these are "***Alpha***" T's (*we will be hand-printing - en mass - our own FairTrade-sourced T's in the near future...!*) they need to be *amazing*!

What ever you need to spend to ***get the best, spend it***!

**Comment by nelsonic** [comment]
***For the Record***: I am a ***massive fan of the teal***, but I'm *not married* to it as "*our*" (*only*) color.
Would it be *possible* to get a couple of *different* colors printed in the same batch/order...?
+ Red Triblend
+ Green Triblend
+ Charcoal-Black Triblend
+ Berry Triblend (*this is* ***seriously distinctive*** *and would stand out from a mile at any hackathon*! )
+ Navy Triblend

That way I could move toward my goal of ***only wearing dwyl T's*** from now on. :wink:

**Comment by nelsonic** [comment]
Seriously, your (*hard work*) should not be *buried* in an issue (*which will get closed and lost*) ... 

![ines-dwyl-tshirts-email](https://cloud.githubusercontent.com/assets/194400/8124355/f171641a-10d1-11e5-9ff6-370462f0ad49.png)

Ok. I know that the "logo" we *paid* for is:

![dwyl-logo-on-grey-tshirt](https://cloud.githubusercontent.com/assets/194400/8124340/b133b0e2-10d1-11e5-8cec-02e05c606bdd.png)

But, given that we are building an App, I feel it makes more sense to use the "***App Icon***" logo you used for the stickers #17 
and since we don't pay per gram/millilitre of ink used we should ***Maximise*** it!

@iteles you have my full support to spend what ever money we need on the T's.
If we fail *hopelessly* at everything, at least people will have T's to show for the work they did. :wink:
