### ISSUE TITLE
Simplify wording of @dwyl's Mission?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#189]
At present we have stated the following mission [10 words]:
# "_Empower people to maximise their personal effectiveness, creativity and happiness._"

See: [What is @dwyl's Mission?](https://github.com/dwyl/start-here/blob/6a9e5a67b38ef47a1a384f6a82c8bc57c4e81847/mission.md#what-is-dwyls-mission)

Could we remove  a few words and make it [6 words]:

# "_Maximise personal effectiveness, <br />creativity and happiness._"

I would _love_ to hear suggestions for improvements 
including entirely different words provided they are similar in spirit. 
(_just avoid the word ["productivity"](https://github.com/nelsonic/nelsonic.github.io/issues/651) because it's not what we're after ..._)

**Comment by iteles** [comment]
Everything dwyl has done until now has been guided by giving people the tools they need to enrich their own lives, make better decisions and allow them to [positively impact the world around them by doing so](https://github.com/dwyl/home/issues/100).
This idea of always learning, improving ourselves and lifting others up has permeated our [values from the very beginning](https://github.com/dwyl/start-here/blob/master/manifesto.md). It's our ❤️.

This makes me feel particularly 'attached' to the `'Empower people to'` as a way of conveying this idea of (to borrow a popular turn of phrase) 'teaching a man to fish' rather than 'giving them a fish'. I feel that removing those words changes the sentiment of our mission entirely to the outside eye rather than simplifying it so I would propose we leave those words in.

What I _would_ propose we do away with is `their personal`, leaving the mission as 8 words:
### "Empower people to maximise effectiveness, creativity and happiness."

This doesn't bind people to navel-gazing, but rather provides leeway for our philosophy of looking inward first but with a view to projecting out, by removing the emphasis on the self.
I'd be curious to test this out and see whether it leaves people a little too rudder-less just by itself.

With regards to **effectiveness, creativity and happiness**, I think these encapsulate everything so well. They're obviously super vague at this stage but that's to be expected of a mission. 
I've been racking my brains to see how to fit in health but it's the underpinning to all of these.
I'm still not totally 💯 on these being the final 3 but for now I don't have an improvement to suggest!

**Comment by nelsonic** [comment]
@iteles agree this is better (_more succinct without losing meaning_). 👍  
if you have time to PR the change, please go for it. (_no rush, just whenevs_) 📝

**Comment by iteles** [comment]
Mission updated in #191. 
@nelsonic Leaving this issue open for further thoughts I assume!

**Comment by nelsonic** [comment]
@iteles we can close it for now if you feel it might _distract_ people or cause someone to think we want to _debate_ the mission. 
I’d like to add the word ***health***, but this I wonder if ***happiness*** covers health... 🤔
Can a person be happy _without_ being healthy?
e.g: could someone have a terminal illness and still be happy?

Also, do we need to _define_ any of the words? Or clarify that one person’s happiness _cannot_ be at the expense of another’s. And creativity is not inventing new weapons, systems of mass surveillance or “attention economy”.

How much _context_ is required? And if clarification is needed, is that a sign that our Mission is not good enough to be “stand alone”?

Maybe this can all be clarified by linking to our code of conduct?

**Comment by iteles** [comment]
I totally agree with you on `health`, I [mentioned above](https://github.com/dwyl/start-here/issues/189#issuecomment-551248609) that I feel like it underpins all of these. 

The key here is that we're not being prescriptive, we're enablers of optimisation within your situation. If you have a terminal illness, you can still choose to optimise your health within those constraints.

On the explanation, I think very few mission statement are resistant to being misconstrued in some way. Mission statements might be very high level but they are then backed up by codes of conduct (as you say), objectives and visions.
Tesla doesn't mention in their mission that not all forms of energy are created equal or that if there is a full transition, they foresee a world where all the people who lose their jobs in oil will have jobs in sustainable energy. But their conduct and supporting statements has shown them to not be malicious.

On specifically not doing things at the expense of others, I also talk about lifting others up in my comment above. For us, that's encapsulated in 'empower others'. If you're making yourself happy at other people's expense, you'd be hard pressed to argue that you are carrying on the mission of empowering others.

It certainly needs other things to convey the _detailed_ meaning but that's not the job of the mission statement.

**Comment by nelsonic** [comment]
Ok, let's close this issue and if anyone in the community is "_confused_" or has any questions, 
they are welcome to open a new issue.
