### ISSUE TITLE
Docker tutorials?

### ISSUE THREAD

**Issue by fmoliveira** [dwyl/start-here#61]
I've noticed @dwyl has choosen Vagrant to setup all their development environments.

I know Docker is a much different approach than Vagrant, but I was just wondering: could Docker tutorials be added to the readmes? For example, a short tutorial on how to setup ES with Docker.

You might say no because @dwyl would want to keep homogeneity of environments across all contributors by using the same Vagrantfile, and I would agree with that if special setups are needed. In case the answer is no, it might be interesting to add a note in this repo that Vagrant is prefered.

But in case of @docdis org, whose goal is to spread knowledge, it might be worthy adding Docker tutorials because it adds an alternative for newcomers to start off the tutorials, thus, reaching more people.

What do you think? /cc @nelsonic @iteles

**Comment by nelsonic** [comment]
@fmoliveira we would *love* to use Docker ... see: https://github.com/dwyl/learn-docker
But... for ***development***, Vagrant has proved easier on Mac...

What OS are you using?

**Comment by fmoliveira** [comment]
@nelsonic  Oh, I see! I wasn't aware of that repo, thanks for the link!

I use Linux and Windows. At home I use Linux all the time. At my job I use Windows all the time and I've been running Docker with Boot2Docker. Though Boot2Docker is now deprecated, they've created a new project called Docker Machine, but I haven't tested it yet. I guess setting up Vagrant could be easier indeed because it doesn't need any other layer atop of it, as Docker needs Docker Machine.

I haven't tried using Docker on Mac. What were the downsides you've faced?

**Comment by nelsonic** [comment]
On a Mac, you are running a Docker on top of VirtualBox. My issue was exposing the TCP ports...

**Comment by fmoliveira** [comment]
Oh, right. My use cases for Docker at my job are different than at home, I'm using it to cross compile for ARM Linux in Windows, so, I didn't need exposing any ports. That's why I didn't came across the same issue as you did.

I think the TCP ports are exposed to the VM IP address, so you need to find out its IP address and use that. I don't know how do to that with Docker Machine, but I'll setup it tomorrow to play around.

**Comment by fmoliveira** [comment]
Port forwarding can be done through VirtualBox VM settings. This will expose ports from the VM to your host OS.

`VM > Settings > Network > Port Forwarding`

It's also necessary to expose your container port when running it. This will expose the container port to the host port, which, in this case, is the Docker VM:

`docker run -p 9200:9200 -d elasticsearch`

It's not too straightforward as Vagrant anyway. :disappointed:

**Comment by howardroark** [comment]
Docker itself is not really virtualization and requires a Linux kernel to run.  It is a clever way to create a system sandbox around a running Linux kernel, part of the reason it is so fast and efficient.  The core idea behind it is that it allows you to run your application parts as separate systems within the same system without burdening it. The idea being that you run your web service and db service as two sandboxes from the get go so you are forced to configure it that way.  Then if you ever need to scale you don't need to change much.

Because OSX runs the BSD kernel you still need to use virtualization to run it.  I think Boot2Docker used Vagrant to load a lightweight Linux system that allowed Docker to run.

While Docker certainly is "quick to boot", it is not super simple get running with on all systems.  In my view Vagrant is best for development because of how much "automatic" configuration it enables.  Out of the box it supports every "provisioner" and you don't really need to find the perfect box... you can just configure it to your liking.

This project does look very promising though.... https://kitematic.com/

**Comment by nelsonic** [comment]
@howardroark agreed, kitematic *looks* great. I just haven't had (*made*) time to use it.
(mostly because Vagrant serves my needs quite well ...)
But ultimately we need a ***beginner-friendly*** way of running our app(s) and if we can use Docker for that, I'm 100% in favour of switching from Vagrant.

**Comment by fmoliveira** [comment]
Thanks a lot for your thoughts @howardroark ! They are indeed very useful for explaining why Vagrant is easier for development.

Now I see why Vagrant has proved to be easier for development. :)

So, I think there's no reason to add Docker instructions to @dwyl and @docdis for now. Vagrant is more beginner-friendly at the moment, as @nelsonic mentioned. Hopefully Kitematic will change that, it looks really awesome!

**Comment by howardroark** [comment]
Yeah, at this point having your whole team able to just run `vagrant up` makes it the best choice in my view.

**Comment by fmoliveira** [comment]
Sure! Thanks a lot @nelsonic and @howardroark for the clarifications!

Closing. :smiley:

**Comment by nelsonic** [comment]
@fmoliveira if we can get Docker working as easy as Vagrant, we'll switch in a Flash.
Docker has *way* more *hype* (*due to their VC Funding paying for a PR person...*)
And as such will be far more recognisable to people. So if you have time to contribute to the https://github.com/dwyl/learn-docker tutorial, we'd be *massively* grateful! :+1:

**Comment by fmoliveira** [comment]
Fine @nelsonic ! I'll do that! :smiley:
